# Generated by Django 4.1.1 on 2022-11-28 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('company_number_of_employees', models.IntegerField()),
                ('your_first_and_last_name', models.CharField(max_length=100)),
                ('are_you_a_hiring_manager', models.CharField(max_length=100)),
                ('your_phone_number', models.IntegerField(unique=True)),
                ('how_you_heard_about_us', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('where_will_an_employee_report_to_work', models.CharField(max_length=100)),
            ],
        ),
    ]
