# Generated by Django 4.1.1 on 2022-11-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_job_is_there_a_planned_start_date_for_this_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='how_quickly_do_you_need_to_hire',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
