# Generated by Django 4.1.1 on 2022-12-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_apply_job_job_benefits_job_job_requirements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='apply',
        ),
        migrations.AddField(
            model_name='apply',
            name='do_you_have_any_previous_work_experience',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='apply',
            name='email',
            field=models.EmailField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='apply',
            name='full_name',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='apply',
            name='percentage_10th',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='percentage_12th',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='percentage_graduation',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='phone_number',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='what_skills_you_have_that_are_relevant_to_the_position_you_applied_for',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='apply',
            name='what_types_of_job_interests_you',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='apply',
            name='work_references',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
