# Generated by Django 4.1.1 on 2022-12-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_apply_apply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='username',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
