# Generated by Django 4.1.1 on 2022-12-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_apply_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apply',
            new_name='Application',
        ),
    ]
